preload = ["./.config/build.ts"]
jsx = "react"
jsxImportSource = "react"
logLevel = "debug"

[define]
"console.log" = "console.debug"
"import.meta.env" = "process.env"
"Bun._hash_" = "crypto.randomUUID()"

[loader]
".tsx" = "tsx"
".css" = "text"
".svg" = "file"
".ts" = "ts"
